In [ ]:
# 파이썬의 기본자료 중 : 리스트, 딕셔너리
# 파이썬에서 데이터를 쉽게 다루기 위한 라이브러리 : 판다스
# 판다스는 표를 다룰때 많이 사용합니다.
# 판다수는 2차원 데이터로 데이터프레임
# 데이터프레임은 인덱스, 컬럼, 행과 열의 번호의 구조
# 데이터프레임은 숫자나 문자나 모든 데이터를 다룰 수 있다.

# 오늘은 여기에 넘파이 라이브러를 잠깐 정리를 하고 갑니다.
# 넘파이는 수치 데이터를 다루는 라이브러입니다.
# 수치 데이터를 다른다는 것은 수학적인 계산을 많이 제공합니다.
# 넘파이에서 1차원 데이터를 벡터라고 하고, 2차원 데이터를 매트릭스
# 3차원 데이터를 텐서라고 합니다. 
# 1차원 데이터는 [ 1 , 2 ,3 ]
# 2차원 데이터는 [[1,2,3],
#               [4,5,6],     
#               [7,8,9]    
#               ]

test


In [ ]:
## 넘파이랑 판다스는 내장 함수가 많습니다. 이 내장함수를 다 외우고 가면
## 베스트지만.. 쉽지 않을 수 있습니다.

## 그때 그때 나오는 함수를 외우는 것이 더 효과적일 수 있다
## 지금 잡아야 할 것은  넘파이인지 판다스 인지는 인지하고 가야 합니다.

In [ ]:
a = [1,2,3]  #파이썬의 리스트 자료형, 넘파이 아님..
b = [4,5,6]
print(a+b)   #파이썬의 기본 자료형인 리스트의 +연산은 연결..

[1, 2, 3, 4, 5, 6]


In [ ]:
import numpy as np
x = np.array(a)  # a리스트로 넘파이 1차원 벡터를 만든다.
y = np.array([10,20,30]) #리스트를 직접 입력하여 넘파이 1차원 벡터
print(x+y)  #넘파이에서는 리스트간 요소를 합한 결과나 나온다.

[11 22 33]


In [4]:
z = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]    
])

In [5]:
print(type(z))
print(z.shape)

<class 'numpy.ndarray'>
(4, 3)


In [6]:
print(z[0])
print(z[1])
print(z[2])
print(z[3])

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [7]:
print(z[0,2])

3


In [ ]:
print(z.flatten())  ## 매트릭스를 1차원 벡터 형식으로 만든다.

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
print(z.sum())

78


In [ ]:
print(z.sum(axis=0))  # 열별로 합을 구한다.

[22 26 30]


In [11]:
print(z.sum(axis=1))  # 행별로 합을 구한다.

[ 6 15 24 33]


In [ ]:
arr = np.array([10,20,30,40,50,60])
print(arr*2)
print(np.max(arr))   # arr 벡터에서 최고값
print(np.sum(arr))   # arr 벡터에서 총합
print(arr[arr >= 40])  # arr 벡터에서 40보다 큰 값.

[ 20  40  60  80 100 120]
60
210
[40 50 60]


In [ ]:
print(arr.shape)

##  판다스의 데이터프레임도 행과 열의 크기를 변경할 수 있지만 잘 안써요
##  넘파이에서는 모든 값이 숫자입니다. 그래서 행과열의 변환을 자주 해요.

arr_2d= arr.reshape(2,3)  ##arr 벡터를 행은 2개, 열은 3개로 변경
print(arr_2d)

arr_2d_1 = arr.reshape(-1,1)
print(arr_2d_1)  ## arr을 그대로 두고 2차원 매트릭스로 바꿈.
                 #행이 6개 열이 1개.. 
                 
arr_2d_1_1 = arr_2d_1.reshape(-1)  ## 2차원 매트릭스를 다시 1차원으로
print(arr_2d_1_1)

(6,)
[[10 20 30]
 [40 50 60]]
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]
[10 20 30 40 50 60]
